AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template for IAM, S3 access, Secrets Manager, Parameter Store, EventBridge, and Lambda.

Parameters:
  User1Email:
    Type: String
    Description: Email of the first user
  User1Username:
    Type: String
    Description: username of the first user
  User2Email:
    Type: String
    Description: Email of the second user
  User2Username:
    Type: String
    Description: username of the second user

Resources:
  S3Group:
    Type: AWS::IAM::Group
    Properties:
      GroupName: S3ReadOnlyGroup
      Policies:
        - PolicyName: S3ReadOnlyPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource: "*"

  EC2Group:
    Type: AWS::IAM::Group
    Properties:
      GroupName: EC2S3ReadOnlyGroup
    Policies:
      - PolicyName: EC2S3ReadOnlyPolicy
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:ListBucket
              Resource: "*"

  IAMUser1:
    Type: AWS::IAM::User
    Properties:
      Groups:
        - !Ref S3Group
      LoginProfile:
        Password: asdfhbjai23423
        PasswordResetRequired: true
      UserName:
        Ref: User1Username

  IAMUser2:
    Type: AWS::IAM::User
    Properties:
      Groups:
        - !Ref S3Group
      LoginProfile:
        Password: asdfhbjai23423
        PasswordResetRequired: true
      UserName:
        Ref: User2Username
